name: Build and Deploy
on:
  push:
    branches:
      - main
      - 'releases/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npx nx format:check

      - name: Run Lint
        run: npx nx affected -t lint --parallel=3

      - name: Run Tests
        run: npx nx test --parallel=3 --configuration=ci

      - name: Build Application
        run: npx nx build --parallel=3

      - name: Archive Production Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/apps/front

permissions:
  contents: write # Allow write permission to GITHUB_TOKEN to commit to deploy branch.
