name: Build and Deploy
on:
  push:
    branches:
      - main
      - 'releases/**'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      actions: 'read'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      #      - name: Set Base SHA for nx affected commands
      #        run: git branch --track main origin/main

      - uses: nrwl/nx-set-shas@v3

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npx nx format:check

      - name: Run Lint
        run: npx nx affected -t lint --parallel=3

      - name: Run Tests
        run: npx nx affected -t test --parallel=3 --configuration=ci

      - name: Build Application
        run: npx nx affected -t build --parallel=3

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: dist/apps/front
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
permissions:
  contents: write # Allow write permission to GITHUB_TOKEN to commit to deploy branch.
